# Generated by Django 3.2.9 on 2021-12-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_alter_movieinfo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='director',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
