# Generated by Django 3.2.9 on 2021-12-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0015_movieinfo_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='estado',
            field=models.CharField(choices=[('AGREGADO RECIENTE', 'AG'), ('MAS OBSERVADO', 'MO'), ('MAYOR VALORACION', 'MV')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='idioma',
            field=models.CharField(choices=[('ES', 'ESPAÑOL'), ('EN', 'INGLES')], max_length=20),
        ),
    ]
